### ISSUE TITLE
I got errors when I run Cud with running discord

### ISSUE THREAD

**Issue by Alexey-T** [TodNaz/cuda_discord_status#15]
```
Python 3.8.10
Init: cuda_discord_status
Init: cuda_macros
Init: cuda_runner
Startup: 530ms, plugins: 400ms (discord_status 371ms, macros 24ms, runner 4ms)
Init: cuda_hilite_occurrences
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 88, in on_change
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_change: KeyError: 'filename'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 88, in on_change
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_change: KeyError: 'filename'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 88, in on_change
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_change: KeyError: 'filename'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 88, in on_change
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_change: KeyError: 'filename'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 84, in on_tab_change
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_tab_change: KeyError: 'filename'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 73, in on_lexer
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_lexer: KeyError: 'filename'
Init: cuda_breadcrumbs
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 70, in on_open
    self.update_presence(ed_self)
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 92, in update_presence
    proj_basename = os.path.splitext(os.path.basename(proj_info['filename']))[0]
KeyError: 'filename'
ERROR: Exception in CudaText for on_open: KeyError: 'filename'
```

**Comment by Alexey-T** [comment]
похоже вы проект дергаете - а у меня сайд-панель закрыта и проекта нету.

**Comment by Alexey-T** [comment]
proj_info['filename']

-->

proj_info.get('filename', '')
