### ISSUE TITLE
new exception

### ISSUE THREAD

**Issue by Alexey-T** [TodNaz/cuda_discord_status#34]
```
Python 3.8.10
Init: cuda_discord_status
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_discord_status/__init__.py", line 22, in __init__
    self.rpc = Presence('913493054747447386')
  File "/home/user/.config/cudatext/py/cuda_discord_status/pypresence/presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/.config/cudatext/py/cuda_discord_status/pypresence/baseclient.py", line 28, in __init__
    raise DiscordNotFound
cuda_discord_status.pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
ERROR: Exception in CudaText for importing cuda_discord_status: DiscordNotFound: Could not find Discord installed and running on this machine.
```

**Comment by Alexey-T** [comment]
при этом надо показывать юзеру ошибу (в статусбаре) типа cannot connect. в консоли эта ошибка не хороша.

**Comment by TodNaz** [comment]
Сделал

**Comment by Cairillic** [comment]
Как?
